# Generated by Django 5.1.1 on 2024-11-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeTiers',
            fields=[
                ('id_type_tiers', models.AutoField(primary_key=True, serialize=False)),
                ('type_tiers', models.CharField(max_length=100)),
            ],
        ),
    ]
