# Generated by Django 5.1.1 on 2024-10-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id_ville', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ville', models.CharField(max_length=100)),
                ('code_ville', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ville',
            },
        ),
    ]
