# Generated by Django 5.1.1 on 2024-11-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localites', '0001_initial'),
        ('typeDeTiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id_intervenant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('raison_social', models.CharField(blank=True, max_length=100, null=True)),
                ('num_stat', models.CharField(blank=True, max_length=50, null=True)),
                ('NIF', models.CharField(blank=True, max_length=50, null=True)),
                ('CIN', models.CharField(blank=True, max_length=50, null=True)),
                ('id_type_tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typeDeTiers.typedetiers')),
                ('id_ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localites.ville')),
            ],
        ),
    ]
